config/routes.rb
Palaver::Application.routes.draw do
  root :to => 'chatrooms#list'
  get '/chatrooms/new' => 'chatrooms#new', :as => :new_chatroom
  get '/chatrooms/:filter' => "chatrooms#list", :as => :chatroom_filter

  get '/twitter' => "main#twitter"
  get "/chatroom/:id/join" => "chatrooms#join", :as => :join_chatroom
  match "/auth/:provider" => 'session#create', :as => :social_login
  match "/auth/:provider/callback" => 'session#create'
  match "/auth/failure" => 'session#failure'
  match "/auth/identity" => 'session#identity', :as => :login
  match "/auth/identity/register" => 'session#register', :as => :register
  match "/logout" => 'session#destroy', :as => :logout
  match "/connection/remove/:id" => 'user#remove_connection', :as => :remove_connection


  get "/:id" => "chatrooms#show", :as => :chatroom
  put "/:id" => "chatrooms#update"
  delete "/:id" => "chatrooms#destroy"

  put "post/reject/:id" => "posts#reject", :as => :reject_post
  put "post/:id/:profile_id" => "posts#assign_to_profile", :as => :post_assign

  delete "/account/:account_id/member/:member_id" => "accounts#remove_member", :as => :remove_member

  resources :chatrooms
  resources :posts
  resources :accounts
  resources :profiles
  resources :user
  resources :session

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
  extend FriendlyId
  include Status
  default_scope where("status != 'destroyed'")
  scope :closed, where(:status => 'closed')
  
  friendly_id :name, use: :history

  include ActiveSupport

  attr_accessible :name, :banned_users, :account_id, :hide_replies, :fbappid, :fbappnamespace, :fpappsecret, :moderation, :slug, :theme_id, :timezone
  attr_accessor :date_start, :date_end

  belongs_to :account
  has_one :owner, :through => :account

  has_many :profiles, :dependent => :destroy
  has_many :users, :through => :profiles
  has_many :celebrities
  has_many :moderators
  has_many :viewers
  has_many :posts

  validates_uniqueness_of :slug

  def banned_profiles
    self.profiles.banned
  end

  def is_profile_banned?(profile)
    self.banned_profiles.include?(profile)
  end

  def is_user_banned?(user)
    if user.class == User
      profiles = user.profiles
      intersection = self.banned_profiles & profiles
      return true if intersection.size > 0
    elsif user.class == Profile
      self.is_profile_banned?(user)
    end
  end

  def messages
    self.posts.where(:parent_id => nil).order('updated_at ASC').open
  end
  
  def join(user)
    
  end
  
  def add_viewer(user)
    unless self.has_user?(user)
      usernames = self.profiles.collect {|u| u.display_name}
      raise ProfileException.new(message: "Display name is already taken") if usernames.include? user.username
      
      viewer = Viewer.create(chatroom: self, user_id: user.id, status: 'open', :display_name => user.username, :gravatar => Digest::MD5.hexdigest(user.email.presence || ""))
      self.viewers << viewer
      
      # begin
      # rescue => e
      # end
    end
  end
  
  def has_user?(user)
    self.users.include?(user)
  end
  
  #  ***********************************************
  #   MODERATOR MANAGEMENT      --- 01-08-2013
  # ***********************************************
  def add_moderator(user)
    moderator = Moderator.new(:chatroom => self, :user_id => user.id, :display_name => user.username)
    moderator.open
  end

  def add_moderators(moderators)
    moderators.each do |moderator|
      add_moderator(moderator)
    end
  end

  def update_moderators(users)
    new_profiles = []
    existing_profiles = self.moderators
    users = users + [self.owner]
    users.each do |user|
      profile = user.get_profile_for_chatroom self
      if profile
        new_profiles << profile
      else
        new_profiles <<  Moderator.new(:chatroom => self, :user_id => user.id, :display_name => user.username)
      end
    end
    update_profiles(new_profiles,existing_profiles,"Moderator")
  end

  #  ***********************************************
  #   CELEBRITY MANAGEMENT      --- 01-08-2013
  # ***********************************************
  def add_celebrity(user)
    self.celebrities.create(:chatroom => self, :user_id => user.id, :display_name => user.username, :status => 'open')
  end

  def update_celebrities(users)
    new_profiles = []
    existing_profiles = self.celebrities
    users.each do |user|
      profile = user.get_profile_for_chatroom self
      if profile
        new_profiles << profile
      else
        new_profiles <<  Celebrity.new(:chatroom => self, :user_id => user.id, :display_name => user.username)
      end
    end
    update_profiles(new_profiles,existing_profiles,"Celebrity")
  end

  #  ***********************************************
  #   CHATROOM PROFILE UPDATES      --- 01-08-2013
  # ***********************************************
  def update_profiles(new_profiles,existing_profiles,type)
    profiles_to_add = new_profiles - existing_profiles
    profiles_to_remove = existing_profiles - new_profiles
    profiles_to_add.each do |prof|
      prof.type = type
      prof.open
    end
    profiles_to_remove.each do |prof|
      prof.destroy
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def list
    @filter = params[:filter] || Chatroom.statuses.first
    @chatrooms = Chatroom.send(@filter)
  end


  def show

    @chatroom = Chatroom.find(params[:id])
    @current_profile = @current_user.get_profile_for_chatroom(@chatroom) if @current_user
    session[:return_url] = join_chatroom_path(@chatroom) unless @current_user

    @show_replies = true
    if @chatroom.hide_replies
      @show_replies = false unless @current_profile
    end
    # Set up subscribe channels
    @reject_channel = "message_rejected_#{@chatroom.id}"
    @push_channel = "message_added_#{@chatroom.id}"
    @answered_channel = nil

    if @current_profile &&  @current_profile.is_a?("Celebrity")
      @posts = @current_profile.questions
      @push_channel = "chatroom_#{@chatroom.id}_celebrity_#{@current_profile.id}"
      @answered_channel = "chatroom_#{@chatroom.id}_celebrity_#{@current_profile.id}_answered"
    else
      @posts = @chatroom.messages
    end
    @in_chat = @chatroom.users.include?(@current_user)
  end

  def join
    @chatroom = Chatroom.find(params[:id])
    
    if !@current_user
      session[:return_url] = chatroom_path(@chatroom)
      redirect_to :login
    else
      @in_chat = @chatroom.has_user?(@current_user)
      unless @in_chat
        begin
          @chatroom.add_viewer(@current_user)
        rescue => error
          redirect_to :edit_profile, :notice => "Your username is already taken in that chat, please edit this profile!"
        end
      else
        redirect_to @chatroom
        
      end
    end
  end

  def edit
    @chatroom = Chatroom.find(params[:id])
    if @chatroom.account.owner != @current_user
      redirect_to chatroom_path(@chatroom)
    end
  end

  def update
    @chatroom = Chatroom.find(params[:id])
    s = @chatroom.update_attributes(params[:chatroom])
    celebs = params[:celebrities] ? User.find(params[:celebrities]) : []
    @chatroom.update_celebrities( celebs )
    mods = params[:moderators] ? User.find(params[:moderators]) : []
    @chatroom.update_moderators( mods )
    if s
      notice = "Chatroom Updated"
    else
      notice = "Chatroom was not updated."
    end
    redirect_to :back, :notice => notice
  end

  def create
    @chatroom = Chatroom.create(params[:chatroom])
    @chatroom.add_moderator(@current_user)
    celebs = params[:celebrities] ? User.find(params[:celebrities]) : []
    @chatroom.update_celebrities( celebs )
    mods = params[:moderators] ? User.find(params[:moderators]) : []
    @chatroom.update_moderators( mods )
    redirect_to @chatroom
  end

  def new
    if !@current_user
      session[:return_url] = new_chatroom_path
      redirect_to :login, :notice => "You must login and have an account first."
    elsif @current_user && !@current_user.account
      session[:return_url] = new_chatroom_path
      redirect_to edit_user_path(@current_user), :notice => "You must have an account before you create a chatroom"
    end
    @chatroom = Chatroom.new
  end

  def destroy
    c = Chatroom.find(params[:id])
    s = c.soft_destroy
    if s
      notice = "Chatroom has been removed."
    else
      notice = "Cannot delete chatroom."
    end
    redirect_to :back, :notice => notice
  end

  def format_post_for_mustache(post)
    {
      in_chat: @in_chat,
      message: post.as_json,
      profile: post.profile.as_json,
      type: post.profile.type.downcase
    }
  end
  helper_method :format_post_for_mustache

end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/chatrooms/_form.html.erb
<%= form_for chatroom do |f| -%>
  <%= f.hidden_field :account_id, value: @current_user.account.id %>
  <div class="control-group">
    <div class="control-label"><%= f.label :name %></div>
    <div class="controls"><%= f.text_field :name, :class => "input-block-level" %></div>
  </div>
  <div class="row">
    <div class="span6">
      <%= f.label :celebrities do %>
        Celebrities
        <%= select_tag :celebrities, options_from_collection_for_select(@current_user.account.members, "id", "name", @chatroom.celebrities.map!{|c| c.user.id}), :multiple => true, :class=>"input-block-level" %>
      <% end %>
    </div>
    <div class="span6">
      <%= f.label :moderators do %>
        Moderators
        <%= select_tag :moderators, options_from_collection_for_select(@current_user.account.members, "id", "name", @chatroom.moderators.map!{|m| m.user.id}), :multiple => true, :class=>"input-block-level" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <%= f.label :moderation, :class => "checkbox" do %>
        <%= f.check_box :moderation %> Require message moderation first?
      <% end %>
      <%= f.label :hide_replies, :class => "checkbox" do %>
        <%= f.check_box :hide_replies %> Hide replies from visitors?
      <% end %>
      <%= f.label :status, "Status"%>
      <%= f.select :status, Chatroom.statuses%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Update/Create", :class=> 'btn btn-success' %>
  </div>
<% end -%>

app/views/chatrooms/_list.html.erb
<div id="chatroom_list" class="row">
  <% if !@chatrooms.blank? %>
  <% for chatroom in @chatrooms %>
  <div class="open_chatroom well span4">
    <h3><%=chatroom.name%></h3>
    <p><strong>Total Users:</strong> <%=chatroom.users.count%></p>
    <ul class="nav nav-pills">
      <% if chatroom.status == 'open' %>
      <li><%=link_to "View", chatroom_path(chatroom.slug) %></li>
      <% end %>
      <% if chatroom.owner == @current_user%>
      <li><%=link_to "Edit", edit_chatroom_path(chatroom) %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <% else %>
    <h3 class="notice no-chats"><%= t(:no_open_chats) %></h3>
  <% end %>
</div>

app/views/chatrooms/_messages.html.erb
<% for post in posts %>
  <article id="message_<%= post.id %>" class="<%= post.profile.type.downcase %> well">
    <div>
      <div class="profile">
        <% if post.profile.thumbnail %>
          <img style="border:1px solid #666" src="<%=post.profile.thumbnail%>">
        <% end %>
        <span class="author"><%= post.profile.display_name %>: <%= post.created_at %></span>
      </div>
      <p><%= post.message %></p>
    </div>
    <div class="reply_form">
      <a href="#" class="reply btn btn-link">Reply:</a>
      <%= render 'posts/form', :parent => post%>
    </div>
    <% if @current_profile &&  @current_profile.type.downcase == "moderator" %>
    <%= render 'moderator_controls', post_id: post.id, chatroom: @chatroom %>
    <% end %>

    <% if @show_replies && post.has_replies? %>
      <%= render 'chatrooms/messages',  :posts => post.replies %>
    <% end %>
  </article>
<% end %>


<script type="text/html" charset="utf-8" id="new_message_template">
  <article id="message_{{post.id}}" class="{{type}} well">
    <div>
      <div class="profile">
        {{#profile.image.thumb.url}}
          <img style="border:1px solid #666" src="{{profile.image.thumb.url}}">
        {{/profile.image.thumb.url}}
        <span class="author">{{profile.display_name}}:</span>
      </div>
      <p>{{post.message}}</p>
    </div>
    <div class="reply_form">
      <a href="#" class="reply btn btn-link">Reply:</a>
      <%= render 'posts/form', :parent => "{{post.id}}" %>
    </div>
    <% if @current_profile &&  @current_profile.type.downcase == "moderator" %>
      <%= render 'moderator_controls', post_id: "{{post.id}}", chatroom: "{{profile.chatroom_id}}" %>
    <% end %>
  </article>
</script>

<!-- Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. -->

app/views/chatrooms/_moderator_controls.html.erb
<section class="moderator_controls">
<ul class="nav nav-pills clearfix">
  <li><%= link_to "Reject", "/post/reject/#{post_id}", method: :put, :remote => true %></li>
  <% if !@chatroom.celebrities.blank? %>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Assign to celebrity: <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <% for celebrity in @chatroom.celebrities %>
        <% unless celebrity.questions.collect{|q|q.id}.include? post_id %>
        <li>
          <%= link_to "/post/#{post_id}/#{celebrity.id}", method: :put do%>
          <%= image_tag(celebrity.thumbnail, :alt => celebrity.display_name, :class => "like", :height => 50) %>
            <span><%= celebrity.display_name %></span>
          <% end %>
        </li>
        <% end %>
      <% end %>
    </ul>
  </li>
  <% end %>
</ul>
</section>

app/views/chatrooms/_profile_form.html.erb
<section id="chatroom_profile" class="span4 pull-right">
<% if @current_profile %>
<h4><%= @current_profile.display_name %> is a <%= @current_profile.type.downcase %></h4>
  <%= form_for @current_profile, :as => :profile, :url => profile_path(@current_profile) do |f| -%>
    <div class="control-group"><%= f.text_field :display_name %></div>
    <div class="control-group">
      <img src="<%= @current_profile.thumbnail %>" class="img-polaroid" /> <%= f.file_field :image %>
    </div>
    <%= f.submit "Update Profile", :class => "btn btn-primary" %>
  <% end -%>
<% else %>
    <%= link_to "Join Chat", join_chatroom_path(@chatroom) %>
<% end %>
</section>

app/views/chatrooms/edit.html.erb
<h2>Edit <%= @chatroom.name %></h2>
<%= render "form", chatroom: @chatroom %>

app/views/chatrooms/list.html.erb
<div class="hero-unit">
  <h1>Start talking...</h1>
  <p>Create the conversation</p>
  <p>
    <%= link_to t(:create_cta,:scope => :chatroom), :new_chatroom, :class=> "btn btn-primary" %>
  </p>
</div>

<ul class="nav nav-pills">
  <% if !Chatroom.statuses.blank? %>
  <% for status in Chatroom.statuses %>
      <li <% if status == @filter %>class="active"<% end %>>
        <%= link_to status.upcase, chatroom_filter_path(status) %>
      </li>
    <% end %>
  <% else %>
  <% end %>
</ul>
<%= render "chatrooms/list" %>

app/views/chatrooms/new.html.erb
<h1><%= t(:create_cta, scope: :chatroom) %></h1>
<%= render 'form', chatroom: @chatroom %>

app/views/chatrooms/show.html.erb
<h1 id="chatroom_welcome"><%= t(:welcome,:scope => :chatroom, :chatroom_name => @chatroom.name) %></h1>

<div id="chatroom"
  data-message-reject-channel="<%= @reject_channel %>"
  data-push-channel="<%= @push_channel %>"
  data-chatroom="<%= @chatroom.id %>"
  <% if @answered_channel %> data-answered-channel="<%= @answered_channel %>"<% end %>
  class="<% unless @in_chat %> not_able_to_chat<% end %>"
>
  <header></header>
  <section id="chat"
  <% if @in_chat %>
  class="<%= @current_profile.type.downcase %>"
  <% end %>
  >
    <%= render 'messages', :posts => @posts %>
  </section>
  <footer></footer>
</div>

<% if @chatroom.open? %>
  <div id="message_post_form">
    <div class="row">
      <% if @in_chat %>
      <div class="span8">
        <h3>Post a question:</h3>
        <%= render 'posts/form', :parent => nil%>
      </div>
      <%= render 'profile_form' %>
    <% elsif !@current_user %>
    <div class="span4">
      <h3>Login with us:</h3>
      <%= form_tag "/auth/identity/callback" do %>
        <div class="field">
          <%= label_tag :nickname %>
          <%= text_field_tag :nickname,"", :class => " input-block-level" %>
        </div>
        <div class="field">
          <%= label_tag :password %>
          <%= password_field_tag :password,"", :class => " input-block-level" %>
        </div>
        <div class="actions"><%= submit_tag "Login", :class=> "btn btn-success" %></div>
      <% end %>
    </div>
    <div class="span4">
      <h3>Login with them:</h3>
      <ul class="nav nav-pills nav-stacked"><%= render "shared/login_menu" %></ul>
    </div>

    <div class="span4">
      <h3>Create and account:</h3>
      <%= render 'session/reg_form', :account => nil %>
    </div>
    <% else %>
      <div class="span12"><%= link_to "Join Chat", join_chatroom_path(@chatroom) %></div>
    <% end %>
    </div>
  </div>
<% else %>
<% end %>