config/routes.rb
Palaver::Application.routes.draw do
  root :to => 'chatrooms#list'
  get '/chatrooms/new' => 'chatrooms#new', :as => :new_chatroom
  get '/chatrooms/:filter' => "chatrooms#list", :as => :chatroom_filter

  get '/twitter' => "main#twitter"
  get "/chatroom/:id/join" => "chatrooms#join", :as => :join_chatroom
  match "/auth/:provider" => 'session#create', :as => :social_login
  match "/auth/:provider/callback" => 'session#create'
  match "/auth/failure" => 'session#failure'
  match "/auth/identity" => 'session#identity', :as => :login
  match "/auth/identity/register" => 'session#register', :as => :register
  match "/logout" => 'session#destroy', :as => :logout
  match "/connection/remove/:id" => 'user#remove_connection', :as => :remove_connection


  get "/:id" => "chatrooms#show", :as => :chatroom
  put "/:id" => "chatrooms#update"
  delete "/:id" => "chatrooms#destroy"

  put "post/reject/:id" => "posts#reject", :as => :reject_post
  put "post/:id/:profile_id" => "posts#assign_to_profile", :as => :post_assign

  delete "/account/:account_id/member/:member_id" => "accounts#remove_member", :as => :remove_member

  resources :chatrooms
  resources :posts
  resources :accounts
  resources :profiles
  resources :user
  resources :session

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, use: :slugged

  attr_accessible :email, :password, :username, :slug, :type
  attr_accessor :name

  attr_encrypted :email, :key => APP_CONFIG['encryption_key'], :encode => true
  attr_encrypted :password, :key => APP_CONFIG['encryption_key'], :encode => true

  has_many :profiles
  has_many :posts, :through => :profiles
  has_one :account

  has_many :connections, :dependent => :destroy
  has_and_belongs_to_many :memberships, :class_name => "Account"
  validates_presence_of :username
  validates_uniqueness_of :slug, :username


  # scope :banned, where(:account_id => nil)

  def name
    self.username
  end

  def get_connection(connection)
    self.connections.find {|c| c.type == "#{connection.to_s.gsub('Connection','')}Connection".classify}
  end

  def has_connection?(connection)
    true if get_connection(connection)
  end

  def add_connection(connection)
    self.connections << connection
  end

  def get_profile_for_chatroom(chatroom)
    self.profiles.unscoped.find_by_chatroom_id_and_user_id(chatroom.id,self.id)
  end


  def self.find_or_create_from_connection(connection)
    unless connection.user
      u = User.create(:username => connection.nickname)
      u.connections << connection
    end
    connection.user
  end

  def self.find_or_create_from_omniauth(auth_hash,password=nil,password_confirmation=nil)
    c = Connection.find_or_create_from_omniauth(auth_hash,password,password_confirmation)
    unless c.user
      u = User.create!(:username => c.nickname)
      u.connections << c
    end
    c.user
  end
  # END OMNIAUTH CONNECTIONS

  private

  def encrypted_email
    read_attribute(:encrypted_email)
  end




end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :check_profile_owner, :only => [:show,:edit, :update]

  def list
  end

  def show
    @account_members = @current_user.account.members if @current_user.account && @current_user.account.members
    render :edit if @user == @current_user
  end

  def new
  end

  def create
  end

   def edit
    redirect_to :profile unless @owner
   end

  def update
    @user.update_attributes(params[:user])
    redirect_to user_path(@user), :notice => "User has been updated!"
  end

   def delete
   end

   def check_profile_owner
     @user = User.find(params[:id])
     @owner = true unless @user != @current_user
   end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
<%= form_for @user, :url => :user do |f| %>
<%= hidden_field_tag :id, @user.slug %>
  <div class="control-group">
    <div class="control-label"><%= f.label :username %></div>
    <div class="controls"><%= f.text_field :username, :class => " input-block-level" %></div>
  </div>
  <div class="control-group">
    <div class="control-label"><%= f.label :slug %></div>

    <div class="controls"><%= f.text_field :slug, :readonly => true, :class=>" input-block-level"  %></div>
  </div>
  <div class="control-group">
    <div class="control-label"><%= f.label :email %></div>
    <div class="controls"><%= f.text_field :email, :class=>" input-block-level" %></div>
  </div>
  <div class="controls"><%= f.submit "Save", :class => 'btn btn-success' %></div>
<% end %>

app/views/user/_form_add_account.erb
<%= form_for usr, :url => usr do |f| %>
  <%= f.hidden_field :account_id, value: account.id %>
  <%= f.submit "add #{usr.username}" %>
<% end %>

app/views/user/_register_user_form.html.erb
<%= form_for @user, :url => :user do |f| %>
  <%= f.label :username %>:
  <%= f.text_field :username %><br />

  <%= f.label :email %>:
  <%= f.text_field :email%><br />

  <%= f.hidden_field :attribute, value:"ted"  %>

  <%= f.submit %>
<% end %>

app/views/user/_user_account_form.html.erb
<%= form_for @user.account || Account.new do |f| -%>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <div class="control-group">
    <div class="control-label"><%= f.label :name %></div>
    <div class="controls"><%= f.text_field :name, :class => " input-block-level" %></div>
  </div>
  <div class="control-group">
    <div class="control-label"><%= f.label :slug %></div>
    <div class="controls"><%= f.text_field :slug, :readonly => true, :class => " input-block-level"  %></div>
  </div>
  <div class="controls"><%= f.submit "Add / Update Account", :class => "btn btn-success" %></div>
<% end -%>

app/views/user/_user_chatroom_list.html.erb
<% if @user.account and @user.account.chatrooms %>
<div class="row">
  <div class="span12">
    <h3>Your Chats</h3>
    <ul class="nav nav-pills">
      <li><%= link_to t(:create_cta,:scope => :chatroom), :new_chatroom, :class=> "btn btn-link" %></li>
    </ul>
  </div>
</div>
<div id="chatroom_list" class="row">
<% @user.account.chatrooms.each_with_index do |chatroom,index| %>
  <div class="user_chatroom well span4">
    <h3><strong>Name:</strong> <%=chatroom.name%></h3>
    <p><strong>Slug:</strong> <%=chatroom.slug%></p>
    <p><strong>Status:</strong> <%=chatroom.status%></p>
    <p><strong>Moderation:</strong> <%=chatroom.moderation%></p>
    <p><strong>Total Users:</strong> <%=chatroom.users.count%></p>
    <ul class="nav nav-pills">
      <li>
        <%=link_to "View", chatroom_path(chatroom.slug) %>
      </li>
      <li>
        <%= link_to "Edit", edit_chatroom_path(chatroom) %>
      </li>
      <li>
        <%= link_to "Delete", chatroom_path(chatroom), :method => :delete, :data => {:confirm => "Are you sure?"} %>
      </li>
    </ul>
  </div>
<% end %>
</div>

<% end %>

app/views/user/edit.html.erb
<% if @user.email %>
  <img src="http://www.gravatar.com/avatar/<%=Digest::MD5.hexdigest(@user.email.downcase)%>?size=100&d=mm">
<%end%>

<div class="row">
  <div class="span8">
    <h3><%= @user.username %></h3>
    <%= render 'form' %>
  </div>
  <div class="span4 pull-right">
    <h3>Account Settings</h3>
    <%= render 'user_account_form' %>
  </div>
</div>
<%= render 'user_chatroom_list' %>
<% if @user.account %>
<div class="row">
  <div class="span4">
    <h3>Account Members</h3>
    <% if !@user.account.members.blank? %>
      <table class="table table-striped table-bordered">
        <tbody>
        <% for user in @user.account.members %>
          <tr>
            <td><%=user.username%></td>
            <td class="actions">
              <%= link_to "", remove_member_path(@user.account,user), :class=>"icon-remove", :data => {confirm: "Are you sure?"}, :title => "Remove from account", :rel => "tooltip", :method => :delete %>
            </td>
          </tr>
      <% end %>
      </tbody></table>
    <% else %>
      <p>No account members</p>
    <% end %>
  </div>
  <div class="span8">
    <h3>Register a Member</h3>
    <%= render('session/reg_form', :account => @user.account)%>
  </div>
</div>
<% end %>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>


<p>Username: <%= @user.username %></p>
<p>slug: <%= @user.slug %></p>
<p>Email: <%= @user.email %></p>

<% if @user === @current_user %>
<%= link_to "Edit User", edit_user_path(@current_user) %>
<% end %>